"""Functions and classes to ask the sistematization question."""

import json
import logging
from pathlib import Path

from langchain.prompts import ChatPromptTemplate
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_openai import ChatOpenAI
from pydantic import SecretStr


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

MODEL = "gpt-3.5-turbo"
TEMPERATURE = 0.7
SISTEMATIZATION_PAPER_PATH = Path("src/aspis/data/sistematization_paper.txt")

SISTEMATIZATION_PROMPT = ChatPromptTemplate.from_template(
    """
You are an AI risk analyst.
The user has a product that they described as follows:
{product_description}

They are concerned about the following AI risk:
{risk_description}

You as an AI risk analyst, should think about this problem in the context of the following paper:
{sistematization_paper}

The product description and the risk description are the background concepts.
Your goal is to formulate follow up questions that have to be asked in order to make
sistematized concepts out of the background concepts.
The final goal is to create a measurement instrument for the AI risk against the product.
This measurement instrument is another LLM that will receive a piece of text generated by
the product and will output a score related to the risk.
The questions should ask for examples of the how the risk surfaces in different use cases of the
product, so those can be used as one-shot examples for the measurement instrument.

Please reply with a maximum of 5 questions in the following JSON format:
["question 1", "question 2"]
"""
)


def get_sistematization_questions(
    product_description: str,
    risk_description: str,
    openai_api_key: str,
) -> list[str] | None:
    """Get the sistematization questions.

    Args:
        product_description: The description of the AI-powered product.
        risk_description: The description of the AI risk the product is exposed to.
        openai_api_key: The OpenAI API key to use the LLM.

    Returns:
        The follow up sistematization questions. Will be None if the model fails to
        return a valid JSON.
    """
    llm = get_llm(openai_api_key)
    response = llm.invoke(
        SISTEMATIZATION_PROMPT.format(
            product_description=product_description,
            risk_description=risk_description,
            sistematization_paper=SISTEMATIZATION_PAPER_PATH.read_text(),
        )
    )

    logger.info(f"Model response: {response.content}")

    try:
        parsed_response = json.loads(str(response.content))
    except Exception:
        logger.exception(f"Error parsing the response from the model: '{response.content}'")
        return None

    if not isinstance(parsed_response, list) or not all(isinstance(q, str) for q in parsed_response):
        logger.error(f"Response is not a list of strings: '{response.content}'")
        return None

    return parsed_response


def get_llm(api_key: str) -> BaseChatModel:
    """Get the LLM object.

    Args:
        api_key: The OpenAI API key to set up the LLM.

    Returns:
        The LLM.
    """
    return ChatOpenAI(model=MODEL, temperature=TEMPERATURE, api_key=SecretStr(api_key))
